In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a #해당 marix 출력

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape #해당 array의 shape를 반환

(2, 3)

In [5]:
a[0]

#a 라는 행렬에 대한 index 0번째 row 반환
#As with built-in Python sequences, NumPy arrays are “0-indexed”

array([1, 2, 3])

In [6]:
a[0] = 10
a

#the array is mutable.

array([[10, 10, 10],
       [ 4,  5,  6]])

In [7]:
a[:3]

#slice indexing of a list copies the elements into a new list,
# but slicing an array returns a view: an object that refers to the data in the original array

array([[10, 10, 10],
       [ 4,  5,  6]])

In [8]:
b = a[3:2]
b

# Modifying the view will modify the original array

array([], shape=(0, 3), dtype=int64)

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a

# array and a list of lists is that an element of the array can be accessed by specifying the index along 
# each axis within a single set of square brackets, separated by commas

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a[1, 3]

print(a)

#It is familiar practice in mathematics to refer to elements of a matrix by the row index first and the column index second. 
# This happens to be true for two-dimensional arrays,
# but a better mental model is to think of the column index as coming last and the row index as second to last. 
# This generalizes to arrays with any number of dimensions.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Array attributes

In [11]:
a.ndim

#전체 차원의 수를 반환
#dimensions of an array

2

In [12]:
a.shape
len(a.shape) == a.ndim

True

<b>nidm</b>은 배열의 차원(~= 축) 을 나타낸다. <br>
<b>shape</b> 은 각 차원에 있는 요소의 수를 나타낸다.

In [13]:
a.size
# total number of elements in array


import math
a.size == math.prod(a.shape)

#array는 dict보단 List와 더 비슷하다.
# list와 마찬가지로 array도 length가 존재한다.
# array의 length는 첫번째 axis(=0번째 축)의 길이와 같다.

True

In [14]:
a.dtype

#Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded

dtype('int64')

In [15]:
z = np.zeros(2)
o = np.ones(2)
# e = np.empty() -> empty() missing required argument 'shape'
e = np.empty((2,2))

print(z)
print(o)
print(e)

#모든 elements가 0인 1차원 array 생성
#if you want 2D array, you should pass a tuple as an argument

[0. 0.]
[1. 1.]
[[0.0e+000 4.9e-324]
 [9.9e-324 1.5e-323]]


In [16]:
np.arange(4) #-> #array([0, 1, 2, 3])

#0,1,2,3 으로 출력이 되는 이유는 array는 index를 사용하기 때문이다.

array([0, 1, 2, 3])

In [17]:
np.arange(2, 9, 2) #-> array([2, 4, 6, 8])
# start, stop, step

array([2, 4, 6, 8])

In [18]:
x = np.ones(2, dtype=np.int64)
print(x)

# create an array of ones, but with integer data type

[1 1]


In [19]:
arr1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr2 = np.array([2, 1, 5, 3, 7, 4, 6, 8])

arrs = arr1.sort() # arr.sort()는 arr 자체를 정렬하고 None을 반환한다.
arrs = np.sort(arr1) # np.sort(arr)는 정렬된 새로운 array를 반환한다.

print(arr2) # arr2는 정렬되지 않은 원본 array
print(arrs) # 정렬된 새로운 array

[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


argsort이는 지정된 축을 따라 간접적으로 정렬된 인덱스를 반환

lexsort이는 여러 키에 대한 간접 안정 정렬

searchsorted정렬된 배열에서 요소를 찾는 함수

partition이는 부분 정렬

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b)) #-> array([1, 2, 3, 4, 5, 6, 7, 8])


#배열 연결


array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)





array([[1, 2],
       [3, 4],
       [5, 6]])

ndarray.ndim배열의 축 또는 차원 수를 반환

ndarray.size배열의 전체 요소 개수를 알려줍니다. 이는 배열의 모양 요소들의 곱.

ndarray.shape이 함수는 배열의 각 차원에 저장된 요소의 개수를 나타내는 정수 튜플을 표시

In [22]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example.ndim #-> 3
array_example.size #-> 24
array_example.shape #-> (3, 2, 4)

(3, 2, 4)

In [23]:
a = np.arange(6)
print('a = ',a)

b = a.reshape(3,2)
print('b = ',b)

# reshape함수는 배열의 모양을 변경하는 데 사용

np.reshape(a, shape=(1, 6), order='C')

a =  [0 1 2 3 4 5]
b =  [[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

1D array -> 2D array

In [24]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [25]:
b = a[np.newaxis, :]
b.shape

#axis는 배열에 새로운 축을 추가하는 데 사용

(1, 6)

In [26]:
row_vector = a[np.newaxis, :]
row_vector.shape

#2D row vector 생성

(1, 6)

In [27]:
col_vector = a[:, np.newaxis]
col_vector.shape

#2D column vector 생성

(6, 1)

In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

b = np.expand_dims(a, axis=1)
b.shape

#배열을 확장하여 지정된 위치(=> 1)에 새로운 축을 추가

c = np.expand_dims(a, axis=0)
c.shape

#배열을 확장하여 지정된 위치(=> 0)에 새로운 축을 추가

(1, 6)

In [29]:
data = np.array([1, 2, 3])

a = data[1] #-> 2 , single element indexing
b = data[0:2] #-> array([1, 2]) , slicing
c = data[1:] #-> array([2, 3]) ,slicing
d = data[-2:] #-> array([2, 3]) ,slicing

print(a)
print(b)
print(c)
print(d)

#Indexing and slicing work as expected for 1D arrays

2
[1 2]
[2 3]
[2 3]


In [30]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a

print(a[a<5]) #-> array([1, 2, 3, 4]) , elements less than 5

[1 2 3 4]


In [31]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2) #-> array([ 2,  4,  6,  8, 10, 12]) ,
# elements divisible by 2

[ 2  4  6  8 10 12]


In [32]:
c = a[(a > 2) & (a < 11)]
print(c)

# & 연산자 == logical AND

five_up = (a > 5) | (a == 5)
print(five_up)

# elements greater than or equal to 5
# | 연산자 == logical OR

[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [33]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5) #5 미만의 요소의 인덱스를 반환

print(b) #-> (array([0, 0, 0, 0]), array([0, 1, 2, 3]))

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [34]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

#When : 존재하는 좌표들의 목록을 생성하고 싶을 때
# 1st : 배열들을 ZIP로 묶기
# 2nd : for문을 통해 좌표 출력

print(a[b])
not_there = np.nonzero(a == 42)
print(not_there)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
[1 2 3 4]
(array([], dtype=int64), array([], dtype=int64))


In [35]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arr1 = a[3:8] #-> array([4, 5, 6, 7, 8]), #slicing from index 3 to 7
arr1


array([4, 5, 6, 7, 8])

In [36]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [37]:
b1 = np.stack((a1,a2))

print(b1)

#array를 세로로 쌓기

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]


In [38]:
b2 = np.hstack((a1,a2))

print(b2)

#array를 가로로 쌓기

[[1 1 3 3]
 [2 2 4 4]]


In [39]:
x = np.arange(1, 25).reshape(2, 12)
x

#array <=> 1~24까지 '생성'
#reshape <=> 2행 12열로 'reshape'

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
np.hsplit(x, 3)

#array를 가로로 3등분

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [41]:
np.vsplit(x, 2)

#array를 세로로 2등분

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [42]:
np.hsplit(x, (3, 4))

#array를 가로로 index 3,4 기준으로 분할

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [44]:
b1 = a[0, :] #-> array([1, 2, 3, 4])
b1

array([1, 2, 3, 4])

In [45]:
b1[0] = 99
b1 #-> array([99,  2,  3,  4])

array([99,  2,  3,  4])

In [46]:
a #-> array([[99,  2,  3,  4],
          #       [ 5,  6,  7,  8],
          #       [ 9, 10, 11, 12]])

#b1을 수정하면 a도 수정된다.

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
b2 = a.copy()

b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Array operation

In [48]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [49]:
data + ones #-> array([2, 3]) , 행렬의 덧셈
data - ones #-> array([0, 1]) , 행렬의 뺄셈
data * ones #-> array([1, 2]) , 행렬의 곱
data / ones #-> array([1., 2.]) , 행렬의 나눗셈

array([1., 2.])

In [53]:
a = np.array([1,2,3,4])

In [ ]:
sum = a.sum() #-> 10 , 배열의 모든 요소의 합
print(sum)  #series

In [52]:
b = np.array([[1, 1],[2, 2]])

In [54]:
b.sum(axis=0) #-> array([3, 3]) , 각 행의 합

array([3, 3])

In [55]:
b.sum(axis=1) #-> array([2, 4]) , 각 열의 합

array([2, 4])

In [56]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2, 4.8, 6.4])

In [57]:
"""cf)"""

x = 1.0
y = 2.0
z = 3.0

daa = np.array([x, y, z])
daa * 1.6

array([1.6, 3.2, 4.8])

In [59]:
data = np.array([1,2,3])

a = data.max()  # -> 3
b = data.min()  # -> 1
c = data.sum()  # -> 6

print(a)
print(b)
print(c)

3
1
6


In [60]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [63]:
print(a.sum())
print(a.min())


4.8595784
0.05093587


In [64]:
print(a.min(axis=0))

[0.12697628 0.05093587 0.26590556 0.5510652 ]
